export const createNewProjectInitialValues = {
  name: "",
  shortName: "",
  email: "",
  phoneNumber: "",
  countryId: "",
  provinceId: "",
  cityId: "",
  address: "",
  externalId: "",
  overdueCharges: "",
  gracePeriod: "",
  transferFee: "",
  cancellationFee: "",
  incomeTaxRateFiler: "",
  incomeTaxRateNonFiler: "",
};
